### ISSUE TITLE
Default Admin/Password, newton soft different versions

### ISSUE THREAD

**Issue by papyr** [piotr-mamenas/performance-app#1]
Hi, whats the default user & pass.

Also, the nugets / dlls are different versions for eg. newton soft in Dtos is v4, but everywhere else its v 10.3
Any chance you will update to bootstrap 4

**Comment by piotr-mamenas** [comment]
Hi, the default user and pass is: Username: DemoUser Password: Secret1#, you can change it in the Seed method of Configuration.cs. Note, as this was my solitude project without much interest from anyone I wasn't very conservative regarding commit practices, that means you might have to go back a commit or two to properly see the data, as I have been in the middle of reworking the authorization and securing the cross domain endpoints. I will fix it along with newtonsoft versions over the weekend.

**Comment by papyr** [comment]
ok thanks, let me know if you want me to test other stuff to help.

Your design is well thought out, with good practices, please do consider adding some notes so this can be used as teaching material. 

Audit: I am trying to work on audits * better user role administration views that let us look at all users in role/with some audit options on what pages he visited. Is this something that would be available if I addded a grid to show the user activity.

**Comment by piotr-mamenas** [comment]
If you pull the latest commit, the session issue is fixed and you can see the data again. The endpoints are now secured. I've been considering adding notes, which I will do once the project is complete, at the moment it changes too much.

Regarding the audit which you probably already got handled, in this app its not currently available out of the box but what you are looking for is easily implementable through a request filter, inside of the filter context you will find things like url/request time etc, just save it along with the currently connected user id and fetch this data wherever you like. Alternatively you can also implement it inside of whatever you handle authorization with. In regards to user online status, the performance app supports it with UserSession table, it contains the login/logout times, the tokens used etc.

Thank you for the kind words :)

I will close the issue.
